// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class ArticleResponse
{
    /// <summary>
    /// 文章ID
    /// </summary>
    public int ArticleId { get; set; }

    /// <summary>
    /// 留言
    /// </summary>
    public string Comment { get; set; }

    /// <summary>
    /// 留言ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 留言者ID
    /// </summary>
    public int UserId { get; set; }

    public DateTime CreateTime { get; set; }

    public virtual Article Article { get; set; }

    public virtual UserInfo User { get; set; }
}