// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class Article
{
    /// <summary>
    /// 文章ID
    /// </summary>
    public int ArticleId { get; set; }

    /// <summary>
    /// 文章標題
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// 文章類型(新聞/討論)
    /// </summary>
    public bool Type { get; set; }

    /// <summary>
    /// 文章創建時間
    /// </summary>
    public DateTime CreateTime { get; set; }

    /// <summary>
    /// 文章內容
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// 文章創作者ID
    /// </summary>
    public int? WriterId { get; set; }

    /// <summary>
    /// 新聞發布者ID
    /// </summary>
    public int? ReleaseBy { get; set; }

    public byte[] Picture { get; set; }

    public byte[] ArticleCover { get; set; }

    public virtual ICollection<ArticleResponse> ArticleResponses { get; set; } = new List<ArticleResponse>();

    public virtual BoManager ReleaseByNavigation { get; set; }

    public virtual UserInfo Writer { get; set; }
}