// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class BoManager
{
    /// <summary>
    /// 管理員ID
    /// </summary>
    public int ManagerId { get; set; }

    /// <summary>
    /// 管理員姓名
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 管理員群組
    /// </summary>
    public string Team { get; set; }

    /// <summary>
    /// 管理員權限
    /// </summary>
    public int? Permissions { get; set; }

    /// <summary>
    /// 管理員帳號
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 管理員密碼
    /// </summary>
    public string Password { get; set; }

    /// <summary>
    /// 管理員電子郵箱
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 管理員手機
    /// </summary>
    public string PhoneNumber { get; set; }

    /// <summary>
    /// 語言
    /// </summary>
    public string Language { get; set; }

    /// <summary>
    /// 管理員狀態
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 管理員創建時間
    /// </summary>
    public DateTime? CreateTime { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}