// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class Event
{
    /// <summary>
    /// 活動標題
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// 活動內容
    /// </summary>
    public string EventContent { get; set; }

    /// <summary>
    /// 活動建立時間
    /// </summary>
    public DateTime? CreateTime { get; set; }

    /// <summary>
    /// 活動ID
    /// </summary>
    public int EventId { get; set; }

    /// <summary>
    /// 活動跑馬燈
    /// </summary>
    public string Marquee { get; set; }

    /// <summary>
    /// 管理者ID
    /// </summary>
    public int ManagerId { get; set; }

    /// <summary>
    /// 活動發放貨幣
    /// </summary>
    public int? Coin { get; set; }

    /// <summary>
    /// 活動發放稱號
    /// </summary>
    public int? Obtain { get; set; }

    /// <summary>
    /// 活動開始時間
    /// </summary>
    public DateTime EventTimeStrat { get; set; }

    /// <summary>
    /// 活動結束時間
    /// </summary>
    public DateTime EventTimeEnd { get; set; }

    /// <summary>
    /// 活動類別
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// 用來新增活動目標數量
    /// </summary>
    public int? EventTarget { get; set; }

    /// <summary>
    /// 用來記錄文章標題是否符合條件
    /// </summary>
    public string? KeyWord { get; set; }

    public virtual ICollection<EventObtain> EventObtains { get; set; } = new List<EventObtain>();

    public virtual BoManager Manager { get; set; }

    public virtual ICollection<Participation> Participations { get; set; } = new List<Participation>();
}