// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class ForumCoin
{
    /// <summary>
    /// 論壇幣ID
    /// </summary>
    public int CoinId { get; set; }

    /// <summary>
    /// 使用者ID
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// 論壇幣獲得來源
    /// </summary>
    public string CoinSource { get; set; }

    /// <summary>
    /// 論壇幣獲得時間
    /// </summary>
    public DateTime AccessTime { get; set; }

    /// <summary>
    /// 論壇幣數量
    /// </summary>
    public int CoinAmount { get; set; }

    /// <summary>
    /// 論壇幣處理狀態
    /// </summary>
    public string Status { get; set; }

    public virtual UserInfo User { get; set; }
}