// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class Login
{
    /// <summary>
    /// 帳號
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 密碼
    /// </summary>
    public string Password { get; set; }

    /// <summary>
    /// 電子郵箱
    /// </summary>
    public string Email { get; set; }

    public bool EmailConfirmed { get; set; }

    public string? EmailVerificationToken { get; set; }

    public virtual UserInfo UserInfo { get; set; }
}