// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class Obtain
{
    /// <summary>
    /// 稱號ID
    /// </summary>
    public int ObtainId { get; set; }

    /// <summary>
    /// 稱號類型
    /// </summary>
    public int Type { get; set; }

    /// <summary>
    /// 稱號名稱
    /// </summary>
    public string Name { get; set; }

    public byte[] Picture { get; set; }

    public int Price { get; set; }

    /// <summary>
    /// 稱號獲取條件
    /// </summary>
    public string Condition { get; set; }

    /// <summary>
    /// 條件類型(尚未決定)
    /// </summary>
    public string ConditionType { get; set; }

    /// <summary>
    /// 條件類型的值(尚未確定)
    /// </summary>
    public int? ConditionValue { get; set; }
    public int? ItemType { get; set; }

    public virtual ICollection<EventObtain> EventObtains { get; set; } = new List<EventObtain>();

    public virtual ICollection<ObtainStatus> ObtainStatuses { get; set; } = new List<ObtainStatus>();
}