// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class Participation
{
    /// <summary>
    /// 活動ID
    /// </summary>
    public int EventId { get; set; }

    /// <summary>
    /// 使用者ID
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// 活動參與時間
    /// </summary>
    public DateTime JoinTime { get; set; }

    /// <summary>
    /// 活動參加狀態
    /// </summary>
    public string Status { get; set; }

    public virtual Event Event { get; set; }

    public virtual UserInfo User { get; set; }
}