// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class Rating
{
    /// <summary>
    /// 好評數
    /// </summary>
    public int? PositiveRating { get; set; }

    /// <summary>
    /// 負評數
    /// </summary>
    public int? NegativeRating { get; set; }

    /// <summary>
    /// 文章ID
    /// </summary>
    public int ArticleId { get; set; }

    /// <summary>
    /// 使用者ID
    /// </summary>
    public int UserId { get; set; }

    public virtual Article Article { get; set; }

    public virtual UserInfo User { get; set; }
}