// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class Relation
{
    public string RelationType { get; set; }

    public int InviterId { get; set; }

    public int InviteeId { get; set; }

    public string Invite { get; set; }

    public virtual UserInfo Invitee { get; set; }

    public virtual UserInfo Inviter { get; set; }
}