// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class UserInfo
{
    /// <summary>
    /// 使用者ID
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// 使用者電子郵箱
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 使用者姓名
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 使用者顯示暱稱
    /// </summary>
    public string Nickname { get; set; }

    /// <summary>
    /// 使用者生理性別
    /// </summary>
    public bool Sex { get; set; }

    /// <summary>
    /// 使用者電話
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// 使用者生日
    /// </summary>
    public DateOnly Birthday { get; set; }

    /// <summary>
    /// 頭像
    /// </summary>
    public byte[]? Photo { get; set; }

    /// <summary>
    /// 簽名檔
    /// </summary>
    public string SignatureLine { get; set; }

    /// <summary>
    /// 是否為登入狀態
    /// </summary>
    public bool Status { get; set; }

    /// <summary>
    /// 論壇幣數量
    /// </summary>
    public int? Wallet { get; set; }
    public Geometry? Position { get; set; }

    public virtual ICollection<ArticleResponse> ArticleResponses { get; set; } = new List<ArticleResponse>();

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    public virtual Login EmailNavigation { get; set; }

    public virtual ICollection<ForumCoin> ForumCoins { get; set; } = new List<ForumCoin>();

    public virtual ICollection<LoginRecord> LoginRecords { get; set; } = new List<LoginRecord>();

    public virtual ICollection<ObtainStatus> ObtainStatuses { get; set; } = new List<ObtainStatus>();

    public virtual ICollection<Participation> Participations { get; set; } = new List<Participation>();

    public virtual ICollection<Relation> RelationInvitees { get; set; } = new List<Relation>();

    public virtual ICollection<Relation> RelationInviters { get; set; } = new List<Relation>();

    public virtual UserStatus UserStatus { get; set; }
}