// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class UserStatus
{
    /// <summary>
    /// 使用者ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 使用者留言數
    /// </summary>
    public int? CommentCount { get; set; }

    /// <summary>
    /// 使用者閱讀數
    /// </summary>
    public int? ReadCount { get; set; }

    /// <summary>
    /// 使用者發文數
    /// </summary>
    public int? PostCount { get; set; }

    /// <summary>
    /// 使用者是否達瀏覽數上限
    /// </summary>
    public bool Status { get; set; }

    /// <summary>
    /// 使用者等級
    /// </summary>
    public int Level { get; set; }


    public virtual UserInfo IdNavigation { get; set; }
}